<?php

namespace JSC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
	public function myEventsIndex($nbPerPage) {
   		$query = $this->_em->createQuery('
			SELECT n FROM JSCPlatformBundle:Event n
			ORDER BY n.id DESC ');

   		$query
		->setMaxResults($nbPerPage);

   		return ($query->getResult());
	}
}
