<?php

namespace JSC\PlatformBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelRepository extends \Doctrine\ORM\EntityRepository
{
	public function myModelsIndex() {
   		$query = $this->_em->createQuery('
			SELECT n FROM JSCPlatformBundle:Model n
			ORDER BY n.priority');

   		return ($query->getResult());
	}
}
